<a href="https://colab.research.google.com/github/MarvinAntillon97/datawarehouse-seguros/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/MarvinAntillon97/datawarehouse-seguros.git

In [18]:
import pandas as pd

In [27]:
url = "https://raw.githubusercontent.com/MarvinAntillon97/datawarehouse-seguros/main/data/clientes.csv"

In [28]:
df = pd.read_csv(url)

In [29]:
#lectura del archivo
df = pd.read_csv(url)
print("Dataset cargado Correctamente")

Dataset cargado Correctamente

In [32]:
display(df.head(10))

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme
5,6,Ricardo López Vásquez,ricardo.lopez.vasquez6@seguro.sv,Hombre,1966/10/15,sonsonate,PYME
6,7,Diego Flores Rojas,diego.flores.rojas0@example.com,m,27-07-1983,SantaAna,Premium
7,8,Karla Ortiz López,karla.ortiz.lopez1@mail.com,M,08-05-1975,SantaAna,Premium
8,9,Juan Flores Morales,juan.flores.morales2@example.com,femenino,14-05-1969,SanMiguel,Regular
9,10,María Aguilar López,maria.aguilar.lopez3@example.com,Masculino,2007-03-14,San Salvador,PREMIUM

BLOQUE 2: Exploracion del DATASET

In [33]:
print("Primeras filas del dataset")
display(df.head())

Primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [34]:
print ("dimensiones del dataset (filas, Columnas)")
print(df.shape)

dimensiones del dataset (filas, Columnas)
(3030, 7)

In [35]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [36]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [37]:
print("Valores nulos por columna")
print(df.isnull().sum())

Valores nulos por columna
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [38]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

LOQUE 3 : LIMPIEZA DE DATOS

In [40]:
#elimina espacios al inicio y al final en columnas de texto
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

In [41]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [42]:
#Normalizar el email
df["email"]=df["email"].str.lower()

In [43]:
#Normalizar genero
df["genero"]=df["genero"].str.upper()

In [44]:
#convertir fecha de nacimiento en formato fecha
df['fecha_nacimiento']=pd.to_datetime(df['fecha_nacimiento'],errors='coerce')

In [45]:
#Normalizar ciudad
df["ciudad"]=df["ciudad"].str.title()

In [47]:
#limpieza de segmento
df["segmento"]=df["segmento"].astype(str)
df["segmento"]=df["segmento"].str.strip()
df["segmento"]=df["segmento"].str.upper()

BLOQUE 4 : VALIDACIÓN DE DATOS

In [48]:
#Crear columna para registrar errores
df["motivo_rechazo"]=""

#Validar id_clinete
df.loc[df["id_cliente"].isnull(),"motivo_rechazo"] +="id_cliente nulo; "